version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: avalanches_postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: avalanches_database
      POSTGRES_USER: avalanches_user
      POSTGRES_PASSWORD: avalanches_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: ["postgres", "-c", "log_statement=all"]

  redis:
    image: redis:latest
    container_name: avalanches_redis_db
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: avalanches_password
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avalanches-container
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
      - redis

  python-app:
    build:
      context: sistema-pagamentos-mock
      dockerfile: Dockerfile
    container_name: sistema-pagamentos-mock-container
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      POSTGRES_DB: avalanches_database
      POSTGRES_USER: avalanches_user
      POSTGRES_PASSWORD: avalanches_password

volumes:
  postgres_data:
  redis_data:
