apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalanches-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avalanches
  template:
    metadata:
      labels:
        app: avalanches
    spec:
      containers:
        - name: avalanches
          image: 779846815660.dkr.ecr.sa-east-1.amazonaws.com/sistema-lanchonete-avalanches:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "300m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
