apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalanches-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avalanches
  template:
    metadata:
      labels:
        app: avalanches
    spec:
      containers:
        - name: avalanches
          image: 779846815660.dkr.ecr.sa-east-1.amazonaws.com/sistema-lanchonete-avalanches:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "300m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          # Adição de variáveis de ambiente
          env:
            - name: DATABASE_DIALECT
              value: "postgres"
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: dbcredentials
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: dbcredentials
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: dbcredentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbcredentials
                  key: password
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: dbcredentials
                  key: db
            - name: TYPEORM_CONNECTION
              value: "postgres"
            - name: TYPEORM_URL
              valueFrom:
                secretKeyRef:
                  name: dbcredentials
                  key: typeorm
