apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  secretObjects:
    - secretName: dbcredentialsv2
      type: Opaque
      data:
        - objectName: host
          key: host
        - objectName: port
          key: port
        - objectName: username
          key: username
        - objectName: password
          key: password
        - objectName: db
          key: db
        - objectName: typeorm
          key: typeorm
  parameters:
    region: sa-east-1
    objects: |
      - objectName: "arn:aws:secretsmanager:sa-east-1:779846815660:secret:dbcredentialsv2-Rcdms4"
        objectAlias: "dbcredentialsv2"
        jmesPath:
          - path: "host"
            objectAlias: "host"
          - path: "port"
            objectAlias: "port"
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
          - path: "db"
            objectAlias: "db"
          - path: "typeorm"
            objectAlias: "typeorm"
